name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u jadharfoush --password-stdin

    - name: Build and Push Docker Image
      run: docker buildx build --platform linux/amd64 -t jadharfoush/chooseyourdress:latest --push DressUp

    - name: Deploy to Private Machine 
      uses: appleboy/ssh-action@master
      with:
        host: 52.57.8.108
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
         docker stop chooseyourdress || true  # Stop existing container if running, ignoring errors if it's not running
         docker rm chooseyourdress || true    # Remove existing container if it exists, ignoring errors if it doesn't exist
          docker rmi $(docker images -q) || true  # Remove all existing images, ignoring errors if there are none
          docker pull jadharfoush/chooseyourdress:latest
          docker run -d --name chooseyourdress -p 80:8000 jadharfoush/chooseyourdress:latest

    - name: Testing Private Machine 
      uses: appleboy/ssh-action@master
      with:
        host: 52.57.8.108
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |      
         sleep 30
         sudo docker exec chooseyourdress /bin/bash -c "python3 manage.py test dailydressme.tests.TemperatureAPITest.test_temperature_equality_on_client"
